/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lemur.nomina.MVC.View;

import com.lemur.nomina.MVC.Controller.AdministradorController;
import com.lemur.nomina.MVC.Model.Administrador;
import java.util.ArrayList;

/**
 *
 * @author tonyc
 */
public class AdministradorManagerView extends javax.swing.JFrame {

    private AdministradorController administradorController;
    private ArrayList<Administrador> administradores;
    private int pos = 0;


    /**
     * Creates new form AdministradorManagerView
     */
    public AdministradorManagerView() {
        initComponents();
        this.administradorController = new AdministradorController();
        this.administradores = administradorController.getAllAdministradores();
        popularTextField(pos);
        this.jTextField_id.setToolTipText("No puedes modificar el id.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_nombre = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jTextField_numHorasTrabajadas = new javax.swing.JTextField();
        jTextField_Salario = new javax.swing.JTextField();
        jTextField_porcentajeCompensacion = new javax.swing.JTextField();
        jButton_anterior = new javax.swing.JButton();
        jButton_siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField_nombre.setText("jTextField1");
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jTextField_id.setText("jTextField1");
        jTextField_id.setName(""); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTextField_numHorasTrabajadas.setText("jTextField1");

        jTextField_Salario.setText("jTextField2");

        jTextField_porcentajeCompensacion.setText("jTextField3");

        jButton_anterior.setText("anterior");
        jButton_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anteriorActionPerformed(evt);
            }
        });

        jButton_siguiente.setText("siguiente");
        jButton_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButton_anterior)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jTextField_nombre)
                    .addComponent(jTextField_numHorasTrabajadas)
                    .addComponent(jTextField_Salario)
                    .addComponent(jTextField_porcentajeCompensacion))
                .addGap(18, 18, 18)
                .addComponent(jButton_siguiente)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_numHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_anterior)
                    .addComponent(jButton_siguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_porcentajeCompensacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anteriorActionPerformed
        // TODO add your handling code here:
        jButton_siguiente.setEnabled(true);
        pos--;
        if(pos == 0){
            jButton_anterior.setEnabled(false);
        } else {
            jButton_anterior.setEnabled(true);
        }
        popularTextField(pos);
    }//GEN-LAST:event_jButton_anteriorActionPerformed

    private void jButton_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteActionPerformed
        // TODO add your handling code here: 
        jButton_anterior.setEnabled(true);
        pos++;
        if(pos == administradores.size()-1){
            jButton_siguiente.setEnabled(false);
        } else {
            jButton_siguiente.setEnabled(true);
        }
        popularTextField(pos);
   
    }//GEN-LAST:event_jButton_siguienteActionPerformed

    private void popularTextField(int pos) {
        Administrador administrador = administradores.get(pos);
        jTextField_id.setText(String.valueOf(administrador.getId()));
        jTextField_nombre.setText(administrador.getNombre());
        jTextField_numHorasTrabajadas.setText(String.valueOf(administrador.getNumHorasTrabajadas()));
        jTextField_Salario.setText(String.valueOf(administrador.getSalario()));
        jTextField_porcentajeCompensacion.setText(String.valueOf(administrador.getPorcentajeCompensacion()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorManagerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_anterior;
    private javax.swing.JButton jButton_siguiente;
    private javax.swing.JTextField jTextField_Salario;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_numHorasTrabajadas;
    private javax.swing.JTextField jTextField_porcentajeCompensacion;
    // End of variables declaration//GEN-END:variables
}
