/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lemur.nomina.MVC.View;

import com.lemur.nomina.MVC.Controller.AdministradorController;
import com.lemur.nomina.MVC.Model.Administrador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author tonyc
 */
public class AdminBrowserCRUD extends javax.swing.JFrame {

    private AdministradorController admnCntrllr;
    private ArrayList<Administrador> administradores;
    private int pos;

    /**
     * Creates new form AdminBrowserCRUD
     */
    public AdminBrowserCRUD() {
        admnCntrllr = new AdministradorController();
        administradores = admnCntrllr.getAllAdministradores();
        pos = 0;
        initComponents();
        loadBrowser(administradores.get(pos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_adminId = new javax.swing.JLabel();
        jTextField_adminId = new javax.swing.JTextField();
        jLabel_adminNombre = new javax.swing.JLabel();
        jTextField_adminNombre = new javax.swing.JTextField();
        jLabel_adminNumHorasTrabajadas = new javax.swing.JLabel();
        jTextField_adminNumHorasTrabajadas = new javax.swing.JTextField();
        jLabel_adminPorcentajeCompensacion = new javax.swing.JLabel();
        jTextField_adminPorcentajeCompensacion = new javax.swing.JTextField();
        jButton_anterior = new javax.swing.JButton();
        jButton_siguiente = new javax.swing.JButton();
        jButton_nuevo = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jLabel_adminSalario = new javax.swing.JLabel();
        jTextField_adminSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nomina: Administrador Browser");

        jLabel_adminId.setText("id");

        jTextField_adminId.setEditable(false);
        jTextField_adminId.setText("jTextField1");

        jLabel_adminNombre.setText("nombre");

        jTextField_adminNombre.setEditable(false);
        jTextField_adminNombre.setText("jTextField1");

        jLabel_adminNumHorasTrabajadas.setText("horas trabajadas");

        jTextField_adminNumHorasTrabajadas.setEditable(false);
        jTextField_adminNumHorasTrabajadas.setText("jTextField1");

        jLabel_adminPorcentajeCompensacion.setText("% compensacion");

        jTextField_adminPorcentajeCompensacion.setEditable(false);
        jTextField_adminPorcentajeCompensacion.setText("jTextField1");

        jButton_anterior.setText("anterior");
        jButton_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anteriorActionPerformed(evt);
            }
        });

        jButton_siguiente.setText("siguiente");
        jButton_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteActionPerformed(evt);
            }
        });

        jButton_nuevo.setText("nuevo");
        jButton_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoActionPerformed(evt);
            }
        });

        jButton_actualizar.setText("actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jButton_eliminar.setText("eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jLabel_adminSalario.setText("salario");

        jTextField_adminSalario.setEditable(false);
        jTextField_adminSalario.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_actualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_adminId, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_adminId, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_adminSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_adminSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_adminPorcentajeCompensacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_adminPorcentajeCompensacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_anterior)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_adminNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_adminNumHorasTrabajadas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_adminNumHorasTrabajadas)
                                    .addComponent(jTextField_adminNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_siguiente)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_adminId)
                    .addComponent(jTextField_adminId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_adminNombre)
                            .addComponent(jTextField_adminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_adminNumHorasTrabajadas)
                            .addComponent(jTextField_adminNumHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_anterior))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_siguiente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_adminPorcentajeCompensacion)
                    .addComponent(jTextField_adminPorcentajeCompensacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_adminSalario)
                    .addComponent(jTextField_adminSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevo)
                    .addComponent(jButton_actualizar)
                    .addComponent(jButton_eliminar))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteActionPerformed
        // TODO add your handling code here:
        pos++;
        loadBrowser(administradores.get(pos));
    }//GEN-LAST:event_jButton_siguienteActionPerformed

    private void jButton_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anteriorActionPerformed
        // TODO add your handling code here:
        pos--;
        loadBrowser(administradores.get(pos));
    }//GEN-LAST:event_jButton_anteriorActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Cancelar",
            "Sí, borralo"};
        int n = JOptionPane.showOptionDialog(this,
                "¿Seguro que desear eliminar al administrador con id: " + administradores.get(pos).getId() + "?",
                "¿Eliminar a " + administradores.get(pos).getNombre() + "?",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[1]);
        if (n == 0 || n == -1) {
            JOptionPane.showMessageDialog(this, "Se canceló la operación.", "Aviso", 1);
        } else {
            admnCntrllr.deleteAdministrador(administradores.get(pos));

            administradores = admnCntrllr.getAllAdministradores();
            pos = 0;
            loadBrowser(administradores.get(pos));
            JOptionPane.showMessageDialog(this, "Se eliminó 1 registro.", "Aviso", 1);

        }

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoActionPerformed
        // TODO add your handling code here:

        AdminCreate adminC = new AdminCreate(this);
        adminC.setVisible(true);
    }//GEN-LAST:event_jButton_nuevoActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        AdminUpdate adminU = new AdminUpdate(this, this.administradores.get(pos));
        adminU.setVisible(true);
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void loadBrowser(Administrador administrador) {
        jTextField_adminId.setText(String.valueOf(administrador.getId()));
        jTextField_adminNombre.setText(administrador.getNombre());
        jTextField_adminNumHorasTrabajadas.setText(String.valueOf(administrador.getNumHorasTrabajadas()));
        jTextField_adminPorcentajeCompensacion.setText(String.valueOf(administrador.getPorcentajeCompensacion()));
        jTextField_adminSalario.setText(String.valueOf(administrador.getSalario()));
        validateButtons();
    }

    private void validateButtons() {
        if (pos == 0) {
            jButton_anterior.setEnabled(false);
        } else {
            jButton_anterior.setEnabled(true);
        }
        if (pos == administradores.size() - 1) {
            jButton_siguiente.setEnabled(false);
        } else {
            jButton_siguiente.setEnabled(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminBrowserCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminBrowserCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminBrowserCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminBrowserCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminBrowserCRUD().setVisible(true);
            }
        });
    }

    public void returnTo() {
        //this.setEnabled(true);
        this.administradores = this.admnCntrllr.getAllAdministradores();
        this.loadBrowser(this.administradores.get(this.administradores.size()));
    }
    
    public void returnToFU() {
        //this.setEnabled(true);
        this.administradores = this.admnCntrllr.getAllAdministradores();
        this.loadBrowser(this.administradores.get(pos));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_anterior;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_nuevo;
    private javax.swing.JButton jButton_siguiente;
    private javax.swing.JLabel jLabel_adminId;
    private javax.swing.JLabel jLabel_adminNombre;
    private javax.swing.JLabel jLabel_adminNumHorasTrabajadas;
    private javax.swing.JLabel jLabel_adminPorcentajeCompensacion;
    private javax.swing.JLabel jLabel_adminSalario;
    private javax.swing.JTextField jTextField_adminId;
    private javax.swing.JTextField jTextField_adminNombre;
    private javax.swing.JTextField jTextField_adminNumHorasTrabajadas;
    private javax.swing.JTextField jTextField_adminPorcentajeCompensacion;
    private javax.swing.JTextField jTextField_adminSalario;
    // End of variables declaration//GEN-END:variables
}
